import Head from 'next/head';

import styles from '@/styles/Home.module.css';

import Signup from '@/components/SignUp';

// const bodyFont = Spinnaker({
//   weight: '400',
//   subsets: ['latin'],
// });

const Home = () => {
  return (
    <>
      <Head>
        <title>Supanova</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/favicon.ico" />
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
        <link rel="manifest" href="/site.webmanifest" />
        <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5" />
        <meta name="msapplication-TileColor" content="#da532c" />
        <meta name="theme-color" content="#ffffff" /> */}
      </Head>
      <main className={styles.app}>
        <Signup />
      </main>
    </>
  );
};

export default Home;
